name: boobook
description: Your library management assistant at school!
publish_to: 'none' 
version: 1.0.1+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # avatar:
  #   git:
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/avatar
    #version: ^0.1.17
  extensions:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/extensions
    #version: ^0.2.4
  # firestore_service:
  #   git: 
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/firestore_service
  #   #version: ^0.2.0
  # firebase_storage_service:
  #   git:
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/firebase_storage_service 
    #version: ^0.3.0 
  # layout_builder:
  #   git:
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/layout_builder 
    #version: ^2.5.4
  localization: 
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/localization
    #ersion: ^1.1.3
  # modal_bottom_sheet:
  #   git:
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/modal_bottom_sheet
  #   #version: ^2.0.2-dev.3
  # models: 
  #   git:
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/models
    #version: ^0.1.3 
  # photo_upload:
  #   git: 
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/photo_upload
  #   #ersion: ^0.5.0
  # sign_in: 
  #   git:
  #     url: https://github.com/julienlebren/flutter_packages
  #     path: packages/sign_in
    #version: ^5.10.0
  purchases:
    git:
      url: https://github.com/julienlebren/flutter_packages
      path: packages/purchases
    ##3#version: ^2.0.1
  badges: ^2.0.2
  barcode_image: ^2.0.1
  barcode_widget: ^2.0.2
  http: ^0.13.4
  cached_network_image: ^3.2.1 
  checkdigit: ^0.3.1
  cloud_firestore: ">=3.1.16"
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  expandable_bottom_sheet: ^1.1.1+1
  firebase_analytics: ">=9.1.8"
  firebase_auth: ">=4.1.3"
  firebase_core: ">=1.24.0"
  firebase_crashlytics: ">=2.9.0"
  firebase_dynamic_links: ">=4.2.4"
  firebase_storage: ">=10.2.16"
  flutter_riverpod: ">=2.1.3"
  riverpod_annotation:
  flutter_slidable: 
  freezed_annotation: 
  image_picker:
  image_cropper: 
  pdf: 
  printing: 
  qr_code_scanner: 
  url_launcher: 
  vibration: 
  json_annotation: 
  cloud_functions: 
  flutter_login_facebook: 
  flutter_libphonenumber:
  google_sign_in: 
  intl: 
  pinput: 
  the_apple_sign_in: 



dev_dependencies:
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner: 
  riverpod_generator:
  freezed: 
  json_serializable: 

dependency_overrides:
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta
  firebase_core_platform_interface: 4.5.1

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: Jack+Input
      fonts:
        - asset: assets/fonts/JackInput.ttf
    - family: AristotelicaSmallCaps
      fonts:
        - asset: assets/fonts/AristotelicaSmallCaps-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
